- name: Installing Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - php-fpm
    - php-mysql
    - php-curl
    - php-gd
    - php-intl
    - php-mbstring
    - php-soap
    - php-xml
    - php-xmlrpc
    - php-zip
  notify: UFW allow Nginx
