- name: Remove Anonymous mysql_user
  community.mysql.mysql_user:
    name: ''
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Removes test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Disallow Remote Root login
  community.mysql.mysql_query:
    login_db: mysql
    query:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
    - FLUSH PRIVILEGES;
    login_unix_socket: /var/run/mysqld/mysqld.sock
